In [1]:
pip install gym[toy_text]



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 4.8/4.8 MB 1.2 MB/s eta 0:00:00


In [1]:
import gym
import random
import numpy as np
import os

In [2]:
env = gym.make("FrozenLake-v1",is_slippery=False,render_mode = "human")
#By setting the property is_slippery=False when creating the environment
#, the slippery surface is turned off and then the environment
#always executes the action chosen by the agent:


#render() : Allows visualizing of the agent and environment interaction.

In [3]:
num_actions = env.action_space.n
num_states = env.observation_space.n
q_table = np.zeros((num_states, num_actions))

In [4]:
print(num_actions)

4


In [5]:
print(num_states)

16


In [6]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
alpha = 0.8 #learning rate
gamma = 0.95 #discount factor The discount factor adjusts the importance of rewards over time.

# Exploration paramters
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.001

rewards = []
epsilon = max_epsilon
n, max_steps = 5000, 30
print(n)
for episode in range(n):
    s = env.reset()
    List1 = list(s)
    s=List1[0]
    total_reward = 0
    for i in range(max_steps):
        if random.uniform(0, 1) < epsilon:
            a = env.action_space.sample()#random action 
        else:
            a = np.argmax(q_table[s][:])#or from q table
        value=env.step(a)#next action
        aList = list(value)#
        s_new=aList[0]#new state
        r=aList[1]#reward
        done=aList[2]#done or not 
        info=aList[3]#
        q_table[s][a] = q_table[s][a] + alpha*(r + gamma*np.max(q_table[s_new]) - q_table[s][a])
        print("Q table")
        
        print(q_table)
        s, total_reward = s_new, total_reward+r
        if done: 
            rewards.append(total_reward)
            epsilon = min_epsilon + (max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)
            break

5000
Q table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Q table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Q table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Q table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
env.close()